name: build
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    env:
      GO111MODULE: "on"
      SSH_RSA_PRIVATE_KEY: ${{ secrets.SSH_RSA_PRIVATE_KEY }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Download Go modules
        run: go mod download

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_RSA_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==

      - name: Install SSH pubkey
        run: echo ${{ secrets.SSH_RSA_PUBLIC_KEY }} > ~/.ssh/id_rsa.pub

      - name: Install SSH agent
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_ED25519_PRIVATE_KEY }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        if: ${{ env.SSH_RSA_PRIVATE_KEY }} != ''
      #- name: Coverage
      #  env:
      #    COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  run: |
      #    go test -race -covermode atomic -coverprofile=profile.cov ./...
      #    GO111MODULE=off go get github.com/mattn/goveralls
      #    $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
      #  if: matrix.go-version == '1.14.x' && matrix.platform == 'ubuntu-latest'
